dist: xenial

language: node_js
node_js:
  - "8"
  - "10"

# Install specific version
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --non-interactive

script:
  - yarn run example:dev
  - yarn run example:prod

# Monitor only these branches
branches:
  only:
  - master
  - dev

# $HOME/.cache/yarn
cache:
  yarn: true
